// productConfig
const fields = [
	'name',
	'shortDescription',
	'description',
	'isActive',
	'unit',
	'unitValue',
	'image',
	'images',
	'category',
	'collection',
	'brand',
	'isFeatured',
	'cost',
	'price',
	'isDiscount',
	'discountType',
	'discount',
	'sku',
	'slug',
	'weight',
	'dimensions.length',
	'dimensions.width',
	'dimensions.height',
	'barcode',
	'tags',
	'allowStock',
	'stock',
	'damage',
	'lowStockAlert',
	'variations',
	'status',
	'customAttributes',
	'customSections',
	'extraAttributes',
	'discountedPrice',
	'vat',
	'isVisible',
	'metaKeywords',
	'metaImage',
	'meta.title',
	'meta.description',
	'faq',
	'createdAt',
	'updatedAt',
];
const tableFields = [
	'name',
	'shortDescription',
	'description',
	'isActive',
	'unit',
	'unitValue',
	'image',
	'images',
	'category',
	'collection',
	'brand',
	'isFeatured',
	'cost',
	'price',
	'isDiscount',
	'discountType',
	'discount',
	'sku',
	'slug',
	'weight',
	'dimensions.length',
	'dimensions.width',
	'dimensions.height',
	'barcode',
	'tags',
	'allowStock',
	'stock',
	'damage',
	'lowStockAlert',
	'variations',
	'status',
	'customAttributes',
	'customSections',
	'extraAttributes',
	'discountedPrice',
	'vat',
	'isVisible',
	'metaKeywords',
	'metaImage',
	'meta.title',
	'meta.description',
	'faq',
	'createdAt',
	'updatedAt',
];
const formFields = [
	{
		sectionTitle: 'Product Information',
		fields: ['image', 'name', 'status'],
	},
	{
		sectionTitle: 'Product Description',
		fields: [
			'category',
			'brand',
			'slug',
			'shortDescription',
			'tags',
			['cost', 'price'],
			'vat',
			['unitValue', 'unit'],
			['sku', 'barcode'],
			['isFeatured'],
		],
	},
	{
		sectionTitle: 'Stock Information',
		fields: [['stock', 'lowStockAlert']],
	},
	{
		sectionTitle: 'Discount Information',
		fields: ['isDiscount', ['discountType', 'discount']],
	},

	{
		sectionTitle: 'Detailed Description',
		fields: ['description'],
	},
	{
		sectionTitle: 'Media',
		fields: ['images'],
	},
	{
		sectionTitle: 'Product Variations',
		description: 'Add variations for this product',
		fields: ['variations'],
	},
	{
		sectionTitle: 'Custom Fields',
		fields: ['customAttributes', 'customSections'],
	},
	{
		sectionTitle: 'Frequently Asked Questions',
		fields: ['faq'],
	},
	{
		sectionTitle: 'SEO',
		description: 'SEO settings for this product',
		fields: ['metaImage', 'meta.title', 'meta.description', 'metaKeywords'],
	},
];

// const route = {
// 	title: 'Employee Management',
// 	subTitle: 'Manage your employee here',
// 	path: 'employees',
// 	button: {
// 		title: 'Add Employee',
// 		isModal: true,
// 	},

// 	menu: [
// 		{ type: 'view-server-modal', title: 'View' },
// 		{ type: 'view-item', title: 'Go To Post' },
// 		{
// 			title: 'Edit Details',
// 			type: 'edit-server-modal',
// 		},

// 		{ type: 'delete', title: 'Delete' },
// 	],
// };
const route = {
	title: 'Products',
	path: 'products',
	export: true,
	// select: {
	// 	show: true,
	// 	menu: multiSelectMenu,
	// },
	button: {
		title: 'Add Product',
		path: '/products/create',
	},
	menu: [
		{ type: 'view-server-modal', title: 'View' },
		{ type: 'view-item', title: 'Go To Post' },
		{
			title: 'Edit Details',
			type: 'edit-server-modal',
		},

		{ type: 'delete', title: 'Delete' },
	],
	// menu: itemMenu,
	// data: viewAllDataFields,
};
const config = {
	fields,
	table: tableFields,
	form: formFields,
	route,
};

export default config;
