import Role from '../role/role.model.js';

const settings: any = {
	name: {
		title: 'Name',
		type: 'string',
		sort: false,
		search: true,
		edit: true,
		required: true,
		trim: true,
		schema: {},
	},
	phone: {
		title: 'Phone',
		type: 'string',
		sort: false,
		search: true,
		edit: true,
		required: true,
		trim: true,
		schema: {},
	},
	email: {
		title: 'Email',
		type: 'string',
		sort: false,
		search: true,
		edit: true,
		required: true,
		trim: true,
		schema: {},
	},
	password: {
		title: 'Password',
		type: 'string',
		sort: false,
		search: true,
		edit: true,
		required: true,
		schema: {},
	},
	preferences: {
		title: 'Preferences',
		type: 'array',
		sort: false,
		search: false,
		edit: true,
		schema: {},
	},
	role: {
		title: 'Role',
		type: 'string',
		sort: true,
		search: false,
		edit: true,
		required: true,
		populate: {
			path: 'role',
			select: 'name',
		},
		filter: {
			name: 'role',
			field: 'role_in',
			type: 'multi-select',
			category: 'model',
			model: Role,
			key: 'name',
			label: 'Role',
			title: 'Filter by Role',
		},
		schema: {
			type: 'data-menu',
			tableType: 'string',
			tableKey: 'role.name',
			model: 'roles',
			displayInTable: true,
		},
	},
	isActive: {
		title: 'Is active',
		type: 'boolean',
		sort: true,
		search: false,
		edit: true,
		required: true,
		filter: {
			name: 'isActive',
			type: 'boolean',
			label: 'Is active',
			title: 'Filter by Is active',
		},
		schema: {},
	},
	joiningDate: {
		title: 'Joining date',
		type: 'date',
		sort: true,
		search: false,
		edit: true,
		filter: {
			name: 'joiningDate',
			type: 'date',
			label: 'Joining date',
			title: 'Filter by Joining date',
		},
		schema: {
			type: 'date-only',
			tableType: 'string',
		},
	},
	image: {
		title: 'Image',
		type: 'uri',
		sort: false,
		edit: true,
		schema: {
			type: 'image',
		},
	},
	nid: {
		title: 'Nid',
		type: 'string',
		sort: false,
		search: true,
		edit: true,
		schema: {},
	},
	nidImage: {
		title: 'Nid image',
		type: 'uri',
		sort: false,
		edit: true,
		schema: {
			type: 'image',
		},
	},
	createdAt: {
		title: 'Created at',
		type: 'date',
		sort: true,
		search: false,
		edit: true,
		filter: {
			name: 'createdAt',
			type: 'date',
			label: 'Created at',
			title: 'Filter by Created at',
		},
		schema: {
			type: 'date-only',
		},
	},
};
export default settings;
