const settings: any = {
	name: {
		title: 'Name',
		type: 'string',
		sort: false,
		search: true,
		edit: true,
		required: true,
		trim: true,
		schema: {},
	},
	location: { title: 'Location', type: 'object', edit: true },
	'location.address': {
		title: 'Location Address',
		type: 'string',
		sort: false,
		search: true,
		edit: true,
		schema: {},
	},
	'location.city': {
		title: 'Location City',
		type: 'string',
		sort: false,
		search: true,
		edit: true,
		schema: {},
	},
	'location.state': {
		title: 'Location State',
		type: 'string',
		sort: false,
		search: true,
		edit: true,
		schema: {},
	},
	'location.country': {
		title: 'Location Country',
		type: 'string',
		sort: false,
		search: true,
		edit: true,
		schema: {},
	},
	'location.zipCode': {
		title: 'Location Zip code',
		type: 'string',
		sort: false,
		search: true,
		edit: true,
		schema: {},
	},
	isActive: {
		title: 'Is active',
		type: 'boolean',
		sort: true,
		search: false,
		edit: true,
		filter: {
			name: 'isActive',
			type: 'boolean',
			label: 'Is active',
			title: 'Filter by Is active',
		},
		schema: {},
	},
	createdAt: {
		title: 'Created at',
		type: 'date',
		sort: true,
		search: false,
		edit: true,
		filter: {
			name: 'createdAt',
			type: 'date',
			label: 'Created at',
			title: 'Filter by Created at',
		},
		schema: {
			type: 'date',
			tableType: 'string',
		},
	},
};
export default settings;
